<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>lab_2_exercises</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="lab_2_exercises_files/libs/clipboard/clipboard.min.js"></script>
<script src="lab_2_exercises_files/libs/quarto-html/quarto.js"></script>
<script src="lab_2_exercises_files/libs/quarto-html/popper.min.js"></script>
<script src="lab_2_exercises_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="lab_2_exercises_files/libs/quarto-html/anchor.min.js"></script>
<link href="lab_2_exercises_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="lab_2_exercises_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="lab_2_exercises_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="lab_2_exercises_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="lab_2_exercises_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">lab_2_exercises</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'dplyr'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from 'package:stats':

    filter, lag</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from 'package:base':

    intersect, setdiff, setequal, union</code></pre>
</div>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">setwd</span>(<span class="st">"/Users/caitlinrasbid/github/lab_2/data/doi_10_5061_dryad_18pm5__v20170130/Itter_et_al_EAP16-0589.R1"</span>)</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>tree_dat <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"tree_dat.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co">#1</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(tree_dat)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 131,386
Columns: 8
$ treeID  &lt;int&gt; 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,…
$ standID &lt;int&gt; 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,…
$ stand   &lt;chr&gt; "A1", "A1", "A1", "A1", "A1", "A1", "A1", "A1", "A1", "A1", "A…
$ year    &lt;int&gt; 1960, 1961, 1962, 1963, 1964, 1965, 1966, 1967, 1968, 1969, 19…
$ species &lt;chr&gt; "ABBA", "ABBA", "ABBA", "ABBA", "ABBA", "ABBA", "ABBA", "ABBA"…
$ age     &lt;int&gt; 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18,…
$ inc     &lt;dbl&gt; 0.930, 0.950, 0.985, 0.985, 0.715, 0.840, 0.685, 0.940, 1.165,…
$ rad_ib  &lt;dbl&gt; 10.78145, 11.73145, 12.71645, 13.70145, 14.41645, 15.25645, 15…</code></pre>
</div>
</div>
<section id="the-structure-is-131386-rows-by-8-columns.-the-dataset-shows-the-8-variables-treeid-standid-stand-year-species-age-inc-and-rad_ib.-the-structure-also-indicates-the-variable-type-for-each-either-double-or-character." class="level2">
<h2 class="anchored" data-anchor-id="the-structure-is-131386-rows-by-8-columns.-the-dataset-shows-the-8-variables-treeid-standid-stand-year-species-age-inc-and-rad_ib.-the-structure-also-indicates-the-variable-type-for-each-either-double-or-character.">The structure is 131,386 rows by 8 columns. The dataset shows the 8 variables, treeID, standID, stand, year, species, age, inc, and rad_ib. The structure also indicates the variable type for each, either double or character.</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co">#2</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>tree_dat <span class="sc">%&gt;%</span></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(standID <span class="sc">==</span> <span class="dv">1</span>) <span class="sc">%&gt;%</span></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tally</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    n
1 979</code></pre>
</div>
</div>
</section>
<section id="there-are-979-trees-in-stand-1." class="level2">
<h2 class="anchored" data-anchor-id="there-are-979-trees-in-stand-1.">There are 979 trees in stand 1.</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co">#3</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>tree_dat <span class="sc">%&gt;%</span></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(species <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"ABBA"</span>, <span class="st">"PIST"</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a><span class="fu">count</span>(species)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  species     n
1    ABBA 13033
2    PIST  4188</code></pre>
</div>
</div>
</section>
<section id="in-abies-balsamea-and-4188-in-pinus-strobus" class="level2">
<h2 class="anchored" data-anchor-id="in-abies-balsamea-and-4188-in-pinus-strobus">13033 in Abies balsamea and 4188 in Pinus strobus</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co">#4</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>last_year <span class="ot">&lt;-</span> <span class="fu">max</span>(tree_dat<span class="sc">$</span>year, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>tree_dat <span class="sc">%&gt;%</span></span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(year <span class="sc">==</span> last_year, age <span class="sc">&gt;</span> <span class="dv">200</span>) <span class="sc">%&gt;%</span></span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tally</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  n
1 7</code></pre>
</div>
</div>
</section>
<section id="there-are-7-trees-older-than-200-years-old-in-the-last-year-of-the-dataset." class="level2">
<h2 class="anchored" data-anchor-id="there-are-7-trees-older-than-200-years-old-in-the-last-year-of-the-dataset.">There are 7 trees older than 200 years old in the last year of the dataset.</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="co">#5</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>tree_dat <span class="sc">%&gt;%</span></span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">slice_max</span>(<span class="at">order_by =</span> age, <span class="at">n =</span> <span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  treeID standID stand year species age  inc rad_ib
1     24       2    A2 2007    PIRE 269 0.37 308.84</code></pre>
</div>
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>oldest_tree <span class="ot">&lt;-</span> tree_dat <span class="sc">%&gt;%</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">slice_max</span>(<span class="at">order_by =</span> age, <span class="at">n =</span> <span class="dv">1</span>)</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(oldest_tree)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  treeID standID stand year species age  inc rad_ib
1     24       2    A2 2007    PIRE 269 0.37 308.84</code></pre>
</div>
</div>
</section>
<section id="the-oldest-tree-is-treeid-24-in-standid-2-with-stand-a2-in-year-2007.-it-is-a-pinus-resinosa-and-is-269-years-old.-the-linear-growth-increment-is-0.37mm-and-the-inside-bark-radius-was-308.84mm." class="level2">
<h2 class="anchored" data-anchor-id="the-oldest-tree-is-treeid-24-in-standid-2-with-stand-a2-in-year-2007.-it-is-a-pinus-resinosa-and-is-269-years-old.-the-linear-growth-increment-is-0.37mm-and-the-inside-bark-radius-was-308.84mm.">The oldest tree is treeID 24 in standID 2, with stand A2 in year 2007. It is a Pinus resinosa and is 269 years old. The linear growth increment is 0.37mm and the inside bark radius was 308.84mm.</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="co">#6</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>tree_dat <span class="sc">%&gt;%</span></span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(year <span class="sc">==</span> <span class="dv">2001</span>) <span class="sc">%&gt;%</span></span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">slice_max</span>(<span class="at">order_by =</span> age, <span class="at">n =</span> <span class="dv">5</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  treeID standID stand year species age   inc  rad_ib
1     24       2    A2 2001    PIRE 263 0.210 306.880
2     25       2    A2 2001    PIRE 259 0.280 156.210
3   1595      24    F1 2001    FRNI 212 0.579 156.267
4   1598      24    F1 2001    FRNI 206 0.394 130.251
5   1712      26    F3 2001    FRNI 206 0.168 154.354</code></pre>
</div>
</div>
</section>
<section id="the-five-oldest-trees-in-2001-are-shown-in-the-table-above" class="level2">
<h2 class="anchored" data-anchor-id="the-five-oldest-trees-in-2001-are-shown-in-the-table-above">The five oldest trees in 2001 are shown in the table above</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="co">#7</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>tree_dat <span class="sc">%&gt;%</span></span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(year <span class="sc">==</span> <span class="dv">2002</span>) <span class="sc">%&gt;%</span></span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">slice_sample</span>(<span class="at">prop =</span> <span class="fl">0.3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    treeID standID stand year species age   inc    rad_ib
1     2025      32    H3 2002    POTR  68 0.265 108.59500
2      461       8    B3 2002    PIBA  22 2.180  80.60800
3     2010      32    H3 2002    BEPA  66 0.380  72.82400
4     1675      26    F3 2002    FRNI  38 0.582  59.64100
5     2038      32    H3 2002    BEPA  70 0.175  57.87300
6     1635      25    F2 2002    FRNI  67 0.796  99.87400
7     1276      20    D6 2002    PIMA  68 0.270  87.32420
8     1049      15    D1 2002    THOC 127 0.725  66.24500
9     1158      18    D4 2002    PIMA  61 0.170  59.59080
10    1768      28    G2 2002    ACSA  66 0.000  56.44500
11    1700      26    F3 2002    FRNI  59 0.179  80.98800
12     836      12    C1 2002    ABBA  20 2.910  49.12280
13      18       2    A2 2002    BEPA 120 0.780 113.92600
14     600      10    B5 2002    PIBA  53 0.840 106.35200
15    1678      26    F3 2002    FRNI  94 0.474 101.71500
16    1764      28    G2 2002    ACSA  49 0.510  90.95500
17     993      14    C3 2002    ABBA  45 0.775 159.63730
18    1263      20    D6 2002    PIMA  63 0.325  72.79320
19     143       5    A6 2002    ABBA  51 0.550  71.90710
20    1124      18    D4 2002    PIMA  61 0.320  52.29640
21      86       4    A5 2002    PIST 103 0.155  96.52000
22     577       9    B4 2002    PIBA  94 0.190 105.28000
23    1550      24    F1 2002    ABBA  31 0.753  48.35075
24     455       8    B3 2002    PIBA  23 2.150  89.54900
25    1021      15    D1 2002    PIMA  35 0.985  57.24920
26    1153      18    D4 2002    PIMA  66 0.180  53.10780
27    1006      14    C3 2002    PIGL  62 0.160  90.60300
28    1067      16    D2 2002    ABBA  51 1.720  64.49190
29    1057      16    D2 2002    THOC 126 0.860 187.81000
30     183       6    B1 2002    PIMA  40 0.850  56.46460
31     347       7    B2 2002    PIRE  22 0.585  51.60000
32    1811      29    G3 2002    ACSA  61 0.195  95.79500
33     911      13    C2 2002    ABBA  37 0.480  57.71105
34    2091      33    H4 2002    BEPA  88 0.027 107.97800
35     614      10    B5 2002    PIMA  46 0.670  49.16800
36     444       8    B3 2002    PIMA  26 0.780  72.04800
37     724      11    B6 2002    PIMA  72 0.355  48.07840
38    1628      25    F2 2002    FRNI  69 0.518  98.67400
39     344       7    B2 2002    PIMA  24 0.790  44.41840
40     771      12    C1 2002    ABBA  14 1.300  37.15745
41     879      12    C1 2002    ABBA  13 2.335  41.54165
42     102       4    A5 2002    PIGL  34 1.540  63.52900
43    2099      33    H4 2002    BEPA  81 0.420  92.14000
44     405       8    B3 2002    PIBA  24 1.455  61.33800
45      98       4    A5 2002    BEPA  52 1.420  47.19000
46    1757      28    G2 2002    ACSA  50 0.395  99.31000
47    1462      22    E2 2002    QURU  78 0.865  54.50500
48     290       7    B2 2002    PIBA  26 0.205  47.78800
49    1577      24    F1 2002    FRNI  61 1.102  48.35600
50     768      12    C1 2002    ABBA  17 1.940  51.94515
51     839      12    C1 2002    ABBA  21 1.995  54.08605
52      88       4    A5 2002    PIST 104 3.115 164.21500
53    1623      25    F2 2002    FRNI  79 0.391  96.61500
54    1096      17    D3 2002    THOC  33 0.885  53.51500
55     702      10    B5 2002    PIMA  49 0.580  60.71200
56     860      12    C1 2002    ABBA  23 0.650  45.08970
57    2039      32    H3 2002    BEPA  68 0.490  68.64600
58    1673      26    F3 2002    FRNI  28 0.440  46.67700
59    1898      30    H1 2002    ACSA  73 0.424  56.51200
60    1261      20    D6 2002    PIMA  61 0.430  77.20140
61     788      12    C1 2002    BEPA  72 0.835 119.32500
62     348       7    B2 2002    PIRE  24 3.695  97.92000
63     907      13    C2 2002    ABBA  20 1.945  47.93625
64    1075      17    D3 2002    ABBA  64 0.785  42.41675
65    2259      35    H6 2002    PIGL  21 1.533  49.80700
66     885      12    C1 2002    ABBA  14 1.150  40.69235
67    1505      23    E3 2002    QURU  37 0.985  44.26000
68     295       7    B2 2002    PIBA  24 0.785  49.07200
69     198       6    B1 2002    PIBA  31 2.145  85.89700
70    1408      21    E1 2002    ACRU  64 0.477  53.23500
71    1637      25    F2 2002    FRNI  76 0.652  48.42200
72     225       6    B1 2002    PIBA  36 0.325  52.29500
73    1112      17    D3 2002    THOC 145 1.440 166.12500
74    1047      15    D1 2002    THOC 103 0.555  74.07000
75      64       3    A4 2002    PIST  70 0.360 137.87500
76    1520      23    E3 2002    QURU  80 0.585  81.93000
77    1607      25    F2 2002    FRNI  77 0.611  83.89500
78    2212      34    H5 2002    PIMA  76 0.268  70.73920
79     317       7    B2 2002    PIMA  21 0.900  76.84120
80    1324      20    D6 2002    PIMA  67 0.075  83.86720
81     419       8    B3 2002    PIBA  25 0.835  78.66500
82    1444      21    E1 2002    QURU  32 0.211  47.85100
83    1157      18    D4 2002    PIMA  60 0.105  55.29020
84    2278      35    H6 2002    PIMA  37 0.592  62.13060
85    1574      24    F1 2002    FRNI 123 1.158  76.59200
86    2281      35    H6 2002    PIMA  37 0.238  47.57640
87     271       6    B1 2002    PIMA  32 0.815  58.98820
88     332       7    B2 2002    PIBA  23 0.650  57.35900
89     236       6    B1 2002    PIBA  34 0.410  75.14800
90     589      10    B5 2002    PIBA  54 1.220  90.42500
91     193       6    B1 2002    BEPA  56 0.085  91.75500
92    2015      32    H3 2002    BEPA  62 0.085  47.48300
93     916      13    C2 2002    ABBA  18 1.375  62.98260
94    1163      18    D4 2002    PIMA  34 0.370  58.76200
95      42       3    A4 2002    PIST  62 1.305 156.70000
96     156       5    A6 2002    PIRE  73 2.155 174.51000
97    1986      32    H3 2002    BEPA  70 0.225  49.34900
98    1206      19    D5 2002    PIMA 108 0.090  49.23840
99    1500      23    E3 2002    QURU  72 0.530  81.49000
100    407       8    B3 2002    PIBA  25 2.525 118.13700
101   2043      32    H3 2002    POTR  65 0.785 102.27000
102   1013      15    D1 2002    ABBA  48 0.360  46.17735
103    943      13    C2 2002    ABBA  20 1.305  46.38890
104   2200      34    H5 2002    BEPA  67 0.351  88.34900
105   1202      19    D5 2002    PIMA  84 0.065  56.32880
106    219       6    B1 2002    PIBA  37 0.725  77.68400
107   1461      22    E2 2002    QURU  77 0.700  57.83500
108    740      11    B6 2002    PIMA  64 1.520  70.97500
109    761      11    B6 2002    PIMA  67 0.675  90.40960
110   1720      27    G1 2002    ACSA 115 0.130 116.22500
111   1899      30    H1 2002    ACSA  56 0.464  81.84300
112    814      12    C1 2002    ABBA  23 1.960  60.20710
113   1473      22    E2 2002    QURU  78 0.940  96.34500
114   2063      33    H4 2002    ABBA  39 0.319  44.87045
115    327       7    B2 2002    PIBA  24 1.615  68.64300
116    861      12    C1 2002    ABBA  15 1.825  46.22360
117   2032      32    H3 2002    ACRU  33 0.790  44.49000
118   1188      18    D4 2002    PIMA  54 0.145  80.63500
119    460       8    B3 2002    PIBA  24 2.315 108.55800
120   1382      20    D6 2002    PIMA  69 0.360  92.81100
121   1646      25    F2 2002    FRNI  70 0.537 103.81800
122    474       8    B3 2002    PIBA  21 2.050  90.31900
123   1472      22    E2 2002    QURU 105 0.795 122.54500
124   1311      20    D6 2002    PIMA  70 0.030  76.19300
125   1998      32    H3 2002    POGR  72 0.700 119.37500
126   2189      34    H5 2002    PIMA  63 0.285 101.48500
127    325       7    B2 2002    POTR  32 0.185  73.51500
128   1035      15    D1 2002    THOC 178 0.315 133.62500
129   1240      20    D6 2002    PIMA  72 0.290  90.58120
130   1488      22    E2 2002    QURU  39 0.995  33.07000
131     80       4    A5 2002    BEPA 121 0.570 130.64400
132   1697      26    F3 2002    FRNI  59 0.434  61.82600
133   1211      19    D5 2002    PIMA 101 0.090  53.79660
134   1612      25    F2 2002    FRNI  48 0.260  66.58800
135    875      12    C1 2002    ABBA  21 1.150  45.88450
136    865      12    C1 2002    ABBA  20 1.430  45.63440
137   1208      19    D5 2002    PIMA  88 0.180  47.22460
138   1539      23    E3 2002    QURU  79 1.075  85.26500
139    727      11    B6 2002    ABBA  33 0.650  44.72980
140    717      11    B6 2002    PIBA  80 0.060  90.67800
141   1622      25    F2 2002    PIGL  27 2.545  55.95600
142    386       7    B2 2002    PIBA  24 0.275  47.77100
143    909      13    C2 2002    ABBA  23 1.555  75.33070
144   1691      26    F3 2002    FRNI  74 0.418  81.46200
145    760      11    B6 2002    PIMA  74 1.000  85.98620
146   1590      24    F1 2002    FRNI  76 0.688  61.93100
147   1005      14    C3 2002    PIGL  53 1.130  64.43000
148   1746      28    G2 2002    ACSA  56 0.000  47.61000
149   2287      35    H6 2002    POTR  30 0.312  74.00300
150   2067      33    H4 2002    BEPA  83 0.566 144.85200
151   1660      25    F2 2002    FRNI  70 0.425  86.09200
152   1161      18    D4 2002    LALA 122 0.210  76.51150
153   1698      26    F3 2002    FRNI  83 0.214  49.57800
154     48       3    A4 2002    PIGL  66 0.500 175.10200
155   1683      26    F3 2002    ACSA  56 1.035  50.65500
156     26       2    A2 2002    PIST 166 2.340 216.82000
157   1671      26    F3 2002    ACSA  34 0.210  42.75500
158   1777      28    G2 2002    ACSA  57 0.150 107.54500
159   1468      22    E2 2002    QURU  85 0.705  59.30000
160   1548      24    F1 2002    ABBA  30 1.418  48.53215
161   2238      35    H6 2002    PIGL  28 1.276  64.73300
162    588      10    B5 2002    BEPA  60 1.250  71.59200
163    274       6    B1 2002    PIMA  37 0.365  64.74540
164   1631      25    F2 2002    FRNI  70 0.287  81.71900
165   1905      30    H1 2002    POTR  79 0.437 135.56900
166    244       6    B1 2002    PIBA  33 1.870  87.56100
167   1593      24    F1 2002    FRNI  68 0.398  65.65000
168    547       9    B4 2002    BEPA  53 0.645  54.29000
169   1103      17    D3 2002    ABBA  47 1.160  35.67745
170    179       6    B1 2002    PIBA  33 3.405  77.99100
171   1553      24    F1 2002    ABBA  36 1.766  38.96770
172    466       8    B3 2002    PIBA  17 0.695  51.51300
173   1024      15    D1 2002    THOC 179 0.635 150.40000
174    686      10    B5 2002    PIBA  53 0.370  72.72900
175    624      10    B5 2002    PIBA  49 0.200  73.69800
176    766      12    C1 2002    ABBA  11 2.185  37.68155
177    426       8    B3 2002    PIBA  25 0.815  73.05500
178    165       6    B1 2002    BEPA  33 1.100  54.08800
179    826      12    C1 2002    ABBA  16 3.055  60.38710
180    719      11    B6 2002    PIBA  79 0.495 118.29000
181   1323      20    D6 2002    PIMA  61 0.380  73.76780
182    659      10    B5 2002    PIBA  58 0.180  96.70100
183   2174      34    H5 2002    BEPA  72 0.003  49.08500
184   1786      28    G2 2002    ACSA  61 0.290  70.52000
185    549       9    B4 2002    BEPA  53 0.810  63.53400
186   1095      17    D3 2002    PIMA  61 1.325  73.73980
187   1910      30    H1 2002    ACRU  57 0.208  46.55400
188   2054      33    H4 2002    ABBA  51 0.747  64.18525
189   1701      26    F3 2002    FRNI  65 0.637  91.55800
190    941      13    C2 2002    ABBA  16 1.615  38.57990
191    592      10    B5 2002    PIBA  56 0.835  94.55400
192    990      14    C3 2002    ABBA  39 1.040  70.23170
193    823      12    C1 2002    ABBA  15 1.480  47.33370
194   1832      29    G3 2002    ACSA  70 0.385  95.40500
195    147       5    A6 2002    BEPA  80 0.000  77.80700
196    136       5    A6 2002    PIRE  78 1.980 165.33500
197    370       7    B2 2002    PIBA  29 0.705  71.56400
198   1466      22    E2 2002    QURU  86 1.245  66.46500
199    491       8    B3 2002    PIBA  22 0.745  70.86100
200   2194      34    H5 2002    POTR  77 0.056  75.56800
201   2064      33    H4 2002    ABBA  44 0.896  76.30140
202    231       6    B1 2002    PIBA  36 0.875  71.59400
203   1486      22    E2 2002    QURU  80 0.635  65.88000
204   1139      18    D4 2002    PIMA  66 0.105  57.85500
205    478       8    B3 2002    PIBA  21 2.055  85.62900
206    299       7    B2 2002    PIBA  25 0.260  74.89200
207    361       7    B2 2002    PIBA  24 1.075  90.83100
208   1958      31    H2 2002    POTR  62 0.350 133.71500
209    859      12    C1 2002    ABBA  12 1.900  35.91235
210   1914      30    H1 2002    ACRU  65 1.132  72.08300
211    936      13    C2 2002    ABBA  25 2.210  72.87080
212   1745      28    G2 2002    ACSA  57 0.250  65.97500
213    639      10    B5 2002    PIBA  54 1.050  88.41900
214    250       6    B1 2002    PIBA  32 0.990 103.42600
215   2095      33    H4 2002    BEPA  84 0.304  83.07900
216   1692      26    F3 2002    FRNI  60 0.390  84.57700
217   1369      20    D6 2002    PIMA  68 0.715  65.21220
218   1589      24    F1 2002    FRNI  76 0.548  65.40400
219   1198      19    D5 2002    PIMA  80 0.245  46.40340
220    951      13    C2 2002    PIMA  30 0.820  59.94180
221   1120      18    D4 2002    PIMA  54 0.265  43.14120
222   1664      25    F2 2002    FRNI  69 0.230  54.22900
223    580       9    B4 2002    PIGL  53 1.620 104.70000
224   1950      31    H2 2002    ABBA  55 0.560  92.88470
225   1107      17    D3 2002    PIMA 122 0.535 155.28800
226    297       7    B2 2002    PIBA  26 0.870  69.95400
227   2266      35    H6 2002    POTR  39 0.091  74.04200
228   1614      25    F2 2002    FRNI  44 0.679  52.80500
229   1608      25    F2 2002    FRNI  64 0.328  80.70300
230    713      11    B6 2002    ABBA  50 3.560  38.80615
231    237       6    B1 2002    PIBA  33 0.095  85.62800
232   1172      18    D4 2002    PIMA  30 0.470  43.67360
233    562       9    B4 2002    PIBA 104 0.830 181.36100
234   1303      20    D6 2002    PIMA  68 0.330  65.82140
235   2104      33    H4 2002    ABBA  42 1.736  61.11915
236   1437      21    E1 2002    ACRU  78 0.639  54.26900
237    284       7    B2 2002    PIBA  22 0.460  50.12400
238    341       7    B2 2002    PIBA  22 1.175 102.00000
239   2147      34    H5 2002    BEPA  66 0.007  55.88300
240   1965      31    H2 2002    ABBA  34 0.995  42.86980
241   1690      26    F3 2002    FRNI  62 0.634  58.88800
242   2272      35    H6 2002    PIGL  22 1.368  35.04200
243    615      10    B5 2002    PIMA  51 0.460  57.87220
244   2020      32    H3 2002    POGR  68 0.775 126.16500
245   1065      16    D2 2002    THOC 134 0.375 136.85500
246   1710      26    F3 2002    FRNI  42 0.322  45.01800
247    557       9    B4 2002    BEPA  59 1.320 123.99600
248    199       6    B1 2002    PIBA  34 1.915  83.03100
249   2138      34    H5 2002    ABBA  31 1.393  49.00405
250   1781      28    G2 2002    ACSA  70 0.695 101.89000
251   1977      31    H2 2002    BEPA  41 0.778 114.25200
252   2005      32    H3 2002    BEPA  71 0.440  86.81100
253   1495      23    E3 2002    ACRU  64 1.150  59.11000
254   1892      30    H1 2002    ACSA  81 0.020  61.27400
255    442       8    B3 2002    PIBA  24 1.345  86.95300
256   1232      19    D5 2002    PIMA  74 0.110  51.76180
257   1852      29    G3 2002    ACSA  79 0.430  91.21500
258   1423      21    E1 2002    QURU  68 0.420  56.02000
259    121       5    A6 2002    ABBA  34 0.755  74.67415
260   1255      20    D6 2002    PIMA  58 0.940 109.19780
261   1602      24    F1 2002    FRNI 180 0.334 111.04300
262    289       7    B2 2002    PIBA  29 0.210  91.28000
263    366       7    B2 2002    PIBA  24 0.385  49.99100
264    134       5    A6 2002    PIMA  76 0.170  59.13840
265    146       5    A6 2002    BEPA  93 0.245  67.12800
266    152       5    A6 2002    PIMA  77 0.090 105.24240
267    712      11    B6 2002    ABBA  58 0.345  75.45405
268   1001      14    C3 2002    PIGL  50 0.800  84.17700
269    869      12    C1 2002    ABBA  15 1.680  36.99705
270    160       5    A6 2002    THOC  73 0.575  57.38500
271   2131      33    H4 2002    PIGL  71 0.742 118.46000
272   2225      35    H6 2002    PIGL  28 1.965 108.75600
273    967      13    C2 2002    ABBA  22 1.020  41.86990
274    864      12    C1 2002    ABBA  15 1.850  51.77065
275   1114      18    D4 2002    LALA  24 0.630  43.32950
276    117       4    A5 2002    PIST 109 1.095 154.19000
277   2133      34    H5 2002    ABBA  29 1.212  38.18045
278   1606      25    F2 2002    FRNI  68 0.520  63.48300
279    942      13    C2 2002    ABBA  32 0.695  67.52485
280   1008      14    C3 2002    PIGL  58 0.565 157.25400
281    844      12    C1 2002    ABBA  15 2.460  60.96720
282    892      12    C1 2002    BEPA  76 0.505 147.61000
283   1853      29    G3 2002    ACSA  84 0.210  53.16000
284   1249      20    D6 2002    PIMA  77 0.225  59.20600
285    750      11    B6 2002    PIBA  76 0.665 109.21900
286   1956      31    H2 2002    POTR  58 0.158  97.53000
287     21       2    A2 2002    PIGL  56 1.180  78.80200
288     55       3    A4 2002    PIST  71 2.310 119.90000
289   1915      30    H1 2002    ACRU  58 1.201  68.48600
290    151       5    A6 2002    PIMA  71 0.570  75.31420
291    670      10    B5 2002    BEPA  59 1.020  62.90500
292   1100      17    D3 2002    ABBA  60 0.395  44.71245
293   1508      23    E3 2002    QURU  44 1.200  40.04500
294    634      10    B5 2002    PIBA  53 1.130  82.25500
295   1640      25    F2 2002    FRNI  74 0.529 105.71500
296   1182      18    D4 2002    PIMA  31 0.725  40.35860
297   1281      20    D6 2002    PIMA  56 0.355  55.77500
298     11       1    A1 2002    BEPA  97 0.520  88.49600
299   2106      33    H4 2002    ABBA  44 1.434  46.91495
300   1260      20    D6 2002    PIMA  62 0.120  60.13600
301   1288      20    D6 2002    PIMA  65 0.690  67.27860
302    718      11    B6 2002    PIBA  70 1.935 140.25200
303   2188      34    H5 2002    PIMA  29 1.404  35.02920
304   1992      32    H3 2002    BEPA  67 0.325  69.15400
305    746      11    B6 2002    ABBA  23 1.430  49.66095
306    962      13    C2 2002    ABBA  20 2.460  50.00615
307   1235      20    D6 2002    LALA  66 0.735  61.81005
308    462       8    B3 2002    PIBA  27 1.935  68.86200
309   1844      29    G3 2002    ACSA  78 0.255 132.73000
310   2170      34    H5 2002    BEPA  79 0.193 107.94000
311    735      11    B6 2002    PIGL  45 1.620  52.17500
312   1125      18    D4 2002    PIMA  54 0.170  47.21600
313    402       8    B3 2002    PIBA  26 2.530  90.28300
314   1155      18    D4 2002    PIMA 128 0.000  65.48420
315   1805      28    G2 2002    ACSA  67 0.410  74.96500
316   1879      30    H1 2002    POGR  81 1.170 163.27500
317   1330      20    D6 2002    PIMA  70 0.000  56.70140
318   1997      32    H3 2002    POGR  68 0.765 121.37000
319   1557      24    F1 2002    BEPA  36 1.264  72.14300
320    754      11    B6 2002    PIBA  70 1.130 102.19800
321   1922      30    H1 2002    ACSA  66 0.383  68.38700
322    843      12    C1 2002    ABBA  12 2.275  38.70195
323   1487      22    E2 2002    QURU  89 0.720  59.17000
324   1228      19    D5 2002    PIMA  92 0.370  60.45580
325    728      11    B6 2002    ABBA  30 0.845  43.93980
326   1847      29    G3 2002    ACSA  76 0.245 160.18500
327     74       4    A5 2002    ABBA  56 1.220  43.20450
328   1672      26    F3 2002    BEPA  29 0.119  75.71500
329   1752      28    G2 2002    ACSA  53 0.160  60.51500
330   1400      21    E1 2002    QURU  27 1.200  42.56500
331    516       8    B3 2002    PIBA  28 0.620  84.84200
332   2263      35    H6 2002    POTR  37 0.261  91.54400
333   2019      32    H3 2002    POGR  72 0.975 103.67500
334    663      10    B5 2002    PIMA  48 0.455  50.44420
335   2239      35    H6 2002    POTR  28 0.418  70.53500
336     97       4    A5 2002    ABBA  48 1.240  67.65395
337   1714      26    F3 2002    FRNI  91 0.268  98.06100
338   2271      35    H6 2002    PIGL  22 0.861  38.33400
339   1312      20    D6 2002    PIMA  68 0.525  74.00300
340    293       7    B2 2002    PIBA  28 0.245  85.62700
341   1753      28    G2 2002    ACSA  44 0.090  56.87000
342    502       8    B3 2002    PIBA  27 0.580  74.57200
343   1250      20    D6 2002    PIMA  68 0.060  61.86580
344   1654      25    F2 2002    FRNI  79 0.377  51.48100
345     33       3    A4 2002    PIGL  61 0.110 105.88400
346    715      11    B6 2002    PIBA  77 1.280 149.03300
347   1333      20    D6 2002    PIMA  59 1.195  74.47000
348   2068      33    H4 2002    BEPA  85 0.086  88.19900
349   1507      23    E3 2002    QURU  55 1.200  56.51000
350    397       7    B2 2002    PIRE  24 1.710  85.76500
351   1693      26    F3 2002    FRNI  72 0.330  82.88800
352   2178      34    H5 2002    BEPA  81 0.286  69.21700
353   1903      30    H1 2002    BEPA  72 0.000  64.93800
354   1706      26    F3 2002    BEPA  69 0.458  88.09100
355   1758      28    G2 2002    ACSA  50 0.220  96.52000
356    693      10    B5 2002    PIBA  48 0.735  66.67700
357   1569      24    F1 2002    FRNI  90 0.400  84.46000
358     52       3    A4 2002    PIGL  70 0.290 123.67700
359   1655      25    F2 2002    FRNI  80 0.525  89.17700
360   1242      20    D6 2002    PIMA  65 0.715  73.35260
361    560       9    B4 2002    BEPA  70 1.385 114.88900
362    759      11    B6 2002    PIMA  74 0.225  70.36480
363    965      13    C2 2002    ABBA  27 1.260  73.04630
364   1653      25    F2 2002    FRNI  66 0.776  64.38600
365    494       8    B3 2002    PIBA  24 0.880  75.73600
366   1121      18    D4 2002    PIMA  61 0.190  49.06820
367   2070      33    H4 2002    BEPA  88 0.172 133.28000
368   2204      34    H5 2002    BEPA  71 0.124  50.83800
369   1632      25    F2 2002    FRNI  68 1.252  55.94200
370   1293      20    D6 2002    PIMA  72 0.240  86.98920
371   2130      33    H4 2002    PIGL  50 0.889  91.25800
372   1791      28    G2 2002    ACSA  63 0.260  57.46500
373    933      13    C2 2002    ABBA  22 1.675  57.02005
374   1082      17    D3 2002    ABBA  57 0.950  51.16830
375    982      14    C3 2002    PIGL  50 0.545 121.82400
376    247       6    B1 2002    PIBA  30 1.610  62.17900
377   1429      21    E1 2002    QURU  58 0.290  54.96500
378   1441      21    E1 2002    QURU  40 0.577  42.08900
379    994      14    C3 2002    ABBA  32 2.615  79.73480
380   1063      16    D2 2002    THOC  94 0.745 175.39500
381    762      11    B6 2002    PIMA  72 0.975 155.48260
382   1971      31    H2 2002    ACRU  45 0.578  78.75600
383   2208      34    H5 2002    BEPA  76 0.194  70.58600
384    800      12    C1 2002    ABBA  23 2.365  45.52870
385   2198      34    H5 2002    ABBA  31 1.500  37.77470
386   2128      33    H4 2002    BEPA  83 0.066  83.06000
387   1138      18    D4 2002    PIMA  51 0.205  50.82160
388   1267      20    D6 2002    PIMA  67 0.430  96.24560
389   2264      35    H6 2002    POTR  33 0.201  91.60700
390   2100      33    H4 2002    BEPA  90 0.501 120.17200
391   1294      20    D6 2002    PIMA  73 0.445 108.89680
392   2270      35    H6 2002    PIGL  58 0.701 169.62000
393   1931      30    H1 2002    QURU  74 0.672 120.03900
394    599      10    B5 2002    PIBA  54 0.925 113.03300
395    818      12    C1 2002    ABBA  12 3.345  48.26300
396   2058      33    H4 2002    ABBA  27 1.158  50.32200
397    459       8    B3 2002    PIBA  20 0.875  72.67000
398   2257      35    H6 2002    PIGL  29 2.318 122.34800
399   2203      34    H5 2002    BEPA  74 0.200 108.94100
400   1946      31    H2 2002    POTR  59 0.145 146.00000
401   1184      18    D4 2002    PIMA  37 0.315  46.36720
402    175       6    B1 2002    PIBA  36 1.865 107.22500
403    268       6    B1 2002    PIMA  39 0.565  89.57840
404    783      12    C1 2002    ABBA  14 1.445  38.62195
405   2102      33    H4 2002    PIGL  49 0.544  58.52600
406    339       7    B2 2002    PIBA  23 0.960  81.40900
407    499       8    B3 2002    PIBA  23 0.500  55.80200
408   1802      28    G2 2002    ACSA  69 0.000  48.87500
409   1310      20    D6 2002    PIMA  69 0.135  78.79400
410    940      13    C2 2002    ABBA  17 1.955  54.34290
411   1733      27    G1 2002    ACRU 104 0.320  87.75000
412   2103      33    H4 2002    PIGL  56 0.973  71.96900
413   1662      25    F2 2002    FRNI  57 0.627  81.35100
414    233       6    B1 2002    PIBA  34 0.935  53.93000
415    294       7    B2 2002    PIBA  27 0.450  72.83000
416   1763      28    G2 2002    ACSA  54 0.395  81.32000
417   1084      17    D3 2002    ABBA  62 0.270  60.75075
418    884      12    C1 2002    ABBA  13 2.055  46.27360
419   1080      17    D3 2002    THOC 133 0.460  92.31500
420   2145      34    H5 2002    BEPA  60 0.139  79.31600
421   1598      24    F1 2002    FRNI 207 0.427 130.67800
422    650      10    B5 2002    PIBA  51 0.250  67.05900
423   1584      24    F1 2002    BEPA  36 0.116  54.46500
424   1576      24    F1 2002    FRNI  74 0.771  66.81200
425   1770      28    G2 2002    ACSA  47 0.530  77.29000
426    377       7    B2 2002    PIBA  28 0.770  61.68300
427   1888      30    H1 2002    ACRU  76 0.730 100.31700
428   1348      20    D6 2002    PIMA  69 0.445  71.31820
429   1991      32    H3 2002    BEPA  75 0.745  97.03400
430    292       7    B2 2002    PIBA  25 0.195  80.84700
431   1033      15    D1 2002    THOC 119 0.330  50.41500
432   1592      24    F1 2002    FRNI  70 0.983  58.34900
433     45       3    A4 2002    PIST  66 0.180  63.39500
434   1711      26    F3 2002    FRNI  37 0.384  47.70900
435   1797      28    G2 2002    ACSA  64 0.185  86.72000
436   1969      31    H2 2002    ACRU  47 0.519  68.85000
437   2159      34    H5 2002    BEPA  80 0.122  73.56000
438    414       8    B3 2002    PIBA  25 0.105  58.81600
439    977      14    C3 2002    ABBA  41 1.500  56.53535
440     35       3    A4 2002    PIST  60 2.235 181.92000
441   2065      33    H4 2002    ABBA  42 0.629  48.16660
442   2150      34    H5 2002    BEPA  80 0.329  93.11100
443    520       8    B3 2002    PIBA  24 0.280  49.50200
444   1480      22    E2 2002    ACRU  44 0.630  43.71500
445   1828      29    G3 2002    ACSA  66 0.155  79.37500
446   1145      18    D4 2002    PIMA  57 0.150  65.08160
447   1217      19    D5 2002    PIMA 104 0.065  54.28040
448    166       6    B1 2002    BEPA  47 0.945  64.21300
449    930      13    C2 2002    ABBA  27 0.790  53.55595
450   1266      20    D6 2002    PIMA  59 0.920  72.29920
451    232       6    B1 2002    PIBA  35 1.045  49.80300
452    393       7    B2 2002    PIRE  25 1.005  91.48500
453     73       4    A5 2002    ABBA  53 1.035 125.44835
454   1963      31    H2 2002    ABBA  50 1.296  64.37575
455    984      14    C3 2002    PIGL  54 0.475  60.31600
456    202       6    B1 2002    PIBA  40 0.065  72.47600
457   1699      26    F3 2002    FRNI  78 0.316  89.84900
458    926      13    C2 2002    POTR  25 0.220  45.51500
459    413       8    B3 2002    PIBA  25 1.230  65.08700
460   2217      34    H5 2002    POTR  79 0.197  99.57200
461    162       6    B1 2002    ABBA  37 0.560  68.61740
462    170       6    B1 2002    BEPA 126 0.150 116.88800
463    777      12    C1 2002    ABBA  16 2.300  58.77200
464    917      13    C2 2002    ABBA  16 2.230  39.96920
465   1643      25    F2 2002    FRNI  78 0.391  70.19300
466    158       5    A6 2002    PIRE  79 1.850 177.67500
467   2144      34    H5 2002    BEPA  80 0.081 109.27600
468    604      10    B5 2002    PIBA  57 1.365 116.60400
469   1045      15    D1 2002    THOC 106 0.495  74.80500
470   1930      30    H1 2002    QURU  74 0.518 101.68100
471    483       8    B3 2002    PIBA  25 0.970  86.33900
472    313       7    B2 2002    PIBA  21 0.000  53.17200
473   1970      31    H2 2002    ACRU  40 1.622  48.82400
474     57       3    A4 2002    PIST  60 2.270 141.01000
475   1954      31    H2 2002    POTR  60 0.460 105.54500
476   1523      23    E3 2002    QURU  75 0.590  75.73500
477    707      10    B5 2002    PIMA  58 0.325  70.93840
478    960      13    C2 2002    ABBA  20 1.475  41.71215
479      4       1    A1 2002    BEPA 114 0.695  61.80100
480    628      10    B5 2002    PIBA  53 0.785  78.06500
481   2053      33    H4 2002    ABBA  44 1.347  50.69225
482   1900      30    H1 2002    ACSA  79 0.184  77.00500
483   1778      28    G2 2002    ACSA  62 0.405  91.84000
484   2232      35    H6 2002    PIGL  28 1.729  90.91400
485    636      10    B5 2002    PIBA  55 0.565  90.35400
486    145       5    A6 2002    ABBA  53 0.545  49.08450
487   1732      27    G1 2002    ACRU 116 0.950 155.62500
488   2048      33    H4 2002    ABBA  26 1.118  49.83990
489   1453      22    E2 2002    ABBA  29 1.070  49.18430
490    379       7    B2 2002    PIBA  24 0.335  56.58800
491    752      11    B6 2002    PIBA  80 0.550 135.98300
492   1357      20    D6 2002    PIMA  65 0.210 112.00020
493   1741      28    G2 2002    ACSA  59 0.565  77.67500
494    318       7    B2 2002    PIMA  21 0.510  44.23080
495    690      10    B5 2002    PIBA  53 0.295  69.93900
496    924      13    C2 2002    BEPA  47 0.845  59.74000
497   1870      30    H1 2002    ACSA  63 0.460  47.71000
498   1864      30    H1 2002    ACRU  75 0.305  48.67500
499   1822      29    G3 2002    ACSA  71 0.205  88.34500
500   1955      31    H2 2002    POTR  64 0.610 148.57500
501   1803      28    G2 2002    ACSA  65 0.130  69.09000
502    390       7    B2 2002    PIRE  25 1.390  71.03000
503   1214      19    D5 2002    PIMA 120 0.120  46.27240
504   1620      25    F2 2002    FRNI  57 0.273  55.79300
505   1525      23    E3 2002    QURU  82 0.415  50.54500
506   1236      20    D6 2002    LALA  76 0.700  82.61255
507   1651      25    F2 2002    FRNI  78 0.387  73.46200
508    998      14    C3 2002    ABBA  19 3.065  57.43425
509    180       6    B1 2002    PIBA  38 1.680  97.14800
510    282       7    B2 2002    PIBA  25 0.980  88.95400
511    778      12    C1 2002    ABBA  16 1.695  70.34365
512    114       4    A5 2002    BEPA  49 0.400  62.05400
513   1902      30    H1 2002    BEPA  75 0.000 136.74800
514   1467      22    E2 2002    QURU  86 0.950  61.19500
515   1396      21    E1 2002    QURU  39 1.170  41.78000
516   1866      30    H1 2002    ACRU  77 0.520  45.61500
517    300       7    B2 2002    PIBA  25 0.760  68.90500
518    947      13    C2 2002    ACRU  44 1.245  67.22000
519    593      10    B5 2002    PIBA  54 1.130  80.81600
520    772      12    C1 2002    ABBA  16 1.190  41.32215
521    330       7    B2 2002    PIBA  26 0.340 102.79000
522   1615      25    F2 2002    FRNI  64 1.441  50.96100
523   1247      20    D6 2002    PIMA  59 0.180  52.71420
524   1431      21    E1 2002    ABBA  19 1.195  33.34500
525    976      13    C2 2002    PIGL  51 0.650 133.53500
526    679      10    B5 2002    PIBA  50 0.515 109.00500
527   2085      33    H4 2002    ACRU  77 0.533  84.24200
528   1627      25    F2 2002    FRNI  69 0.392  64.30900
529    535       9    B4 2002    BEPA  59 1.465  76.75600
530   2168      34    H5 2002    ABBA  58 0.779  90.95625
531   2286      35    H6 2002    POTR  35 0.307 108.17900
532    256       6    B1 2002    PIMA  47 0.875  97.93020
533    587      10    B5 2002    BEPA  60 0.905  59.52600
534    104       4    A5 2002    PIST 106 1.000 114.61500
535   1668      25    F2 2002    FRNI  84 0.473  83.70900
536   1586      24    F1 2002    FRNI 144 0.414 122.63500
537     38       3    A4 2002    PIST  67 0.355  93.93500
538   1037      15    D1 2002    PIMA  43 0.820  84.78900
539    906      12    C1 2002    POTR  17 0.310  49.16500
540    505       8    B3 2002    PIBA  23 0.190  55.31900
541    631      10    B5 2002    PIBA  55 1.220  94.41500
542    769      12    C1 2002    ABBA  13 1.540  37.62460
543    949      13    C2 2002    PIBA  81 1.035 163.68000
544   2202      34    H5 2002    BEPA  79 0.272  71.07800
545   2066      33    H4 2002    ABBA  59 0.427  72.84900
546   1265      20    D6 2002    PIMA  59 0.440  72.65060
547   2121      33    H4 2002    BEPA  70 0.000  79.33100
548   1938      31    H2 2002    ABBA  57 0.620  51.29400
549     90       4    A5 2002    ABBA  48 1.230  43.73185
550   1456      22    E2 2002    QURU  84 1.180  86.57000
551    167       6    B1 2002    BEPA  57 0.040  55.11800
552   1272      20    D6 2002    PIMA  64 0.460  89.54500
553    246       6    B1 2002    PIBA  32 0.895  65.24900
554   1996      32    H3 2002    POGR  65 0.705 102.01500
555   1667      25    F2 2002    FRNI  78 0.400  71.38400
556   2161      34    H5 2002    POTR  75 0.226  90.92300
557    546       9    B4 2002    BEPA  62 0.675  61.35500
558    641      10    B5 2002    PIBA  52 2.155 107.79500
559    649      10    B5 2002    PIBA  55 0.395  63.38500
560    756      11    B6 2002    PIBA  82 0.475 151.44300
561    135       5    A6 2002    PIMA  79 0.535 207.67240
562   1151      18    D4 2002    PIMA  62 0.135  58.13480
563   1960      31    H2 2002    POTR  68 0.748 120.10600
564   1346      20    D6 2002    PIMA  71 0.090  60.23840
565   1591      24    F1 2002    FRNI  78 0.422  59.77400
566    989      14    C3 2002    POTR  67 0.085 117.61500
567    171       6    B1 2002    BEPA  44 0.490  69.47100
568   1849      29    G3 2002    ACSA  82 0.120  63.99500
569    722      11    B6 2002    PIMA  74 0.470 103.03980
570    359       7    B2 2002    PIBA  24 1.165 105.77600
571    485       8    B3 2002    PIBA  22 0.680  74.23800
572   2279      35    H6 2002    PIMA  40 0.767  55.95600
573   1381      20    D6 2002    PIMA  61 0.390  76.42140
574   2181      34    H5 2002    BEPA  80 0.138  70.42600
575   1476      22    E2 2002    QURU  85 1.140 109.12000
576   1881      30    H1 2002    POGR  79 0.895 125.55000
577   1959      31    H2 2002    POTR  66 0.345 124.04500
578   2267      35    H6 2002    POTR  62 0.507 137.20400
579   2206      34    H5 2002    BEPA  68 0.169  56.65500
580   1838      29    G3 2002    ACSA  73 0.080  81.74000
581    510       8    B3 2002    PIBA  27 1.060  94.07100
582    422       8    B3 2002    PIBA  22 0.895  50.25900
583   1775      28    G2 2002    ACRU  75 0.695 112.98500
584    742      11    B6 2002    PIMA  36 2.475  86.19300
585     91       4    A5 2002    ABBA  48 1.175  55.51055
586   1535      23    E3 2002    QURU  82 1.135 112.40500
587   1191      18    D4 2002    PIMA  36 0.180  52.63660
588    583      10    B5 2002    ABBA  51 0.155  47.14735
589   1039      15    D1 2002    PIMA  70 0.995 114.35700
590    846      12    C1 2002    ABBA  12 2.470  32.53970
591   2072      33    H4 2002    BEPA  89 0.332 112.60600
592   1920      30    H1 2002    ACSA  81 0.000  86.97300
593   1680      26    F3 2002    FRNI 134 0.482 157.98800
594   1663      25    F2 2002    FRNI  79 0.442  72.31100
595   1665      25    F2 2002    FRNI  68 1.197  57.41900
596    481       8    B3 2002    ABBA  18 1.695  46.71605
597   1513      23    E3 2002    ACRU  73 0.300  49.10500
598    373       7    B2 2002    PIBA  27 0.000  61.71300
599   1841      29    G3 2002    ACSA  70 0.330  90.03000
600    703      10    B5 2002    PIMA  55 0.590  84.94040
601   1927      30    H1 2002    BEPA  81 0.000 171.40700
602   1734      27    G1 2002    ACSA 113 0.010 112.54000
603   2078      33    H4 2002    ABBA  48 1.028  59.34355
604   2077      33    H4 2002    ABBA  57 0.859  89.42545
605    571       9    B4 2002    BEPA  38 3.620  71.51900
606    658      10    B5 2002    PIBA  58 1.145  92.40900
607   1413      21    E1 2002    PIST  24 2.060 122.64500
608   1386      21    E1 2002    ACRU  34 1.383  46.76900
609    189       6    B1 2002    PIST  33 1.625  56.26000
610   1440      21    E1 2002    QURU  59 0.445  48.74900
611   1216      19    D5 2002    PIMA 106 0.070  53.95660
612    320       7    B2 2002    PIRE  21 1.785  53.28000
613   2000      32    H3 2002    POGR  70 1.420 115.83500
614    744      11    B6 2002    ABBA  24 1.430  43.31185
615   1940      31    H2 2002    ABBA  46 1.005  62.73270
616    584      10    B5 2002    BEPA  61 0.775  44.80700
617    915      13    C2 2002    ABBA  21 1.660  85.49460
618   1587      24    F1 2002    FRNI 135 0.363  59.12700
619   2165      34    H5 2002    ABBA  39 0.481  41.97745
620    184       6    B1 2002    PIMA  54 0.480  95.36800
621   1313      20    D6 2002    PIMA  55 1.135  59.95900
622    468       8    B3 2002    PIBA  21 1.270  66.23000
623    123       5    A6 2002    BEPA  82 0.625  91.05100
624   1379      20    D6 2002    PIMA  68 0.325  87.59540
625    349       7    B2 2002    PIRE  19 1.005  45.64000
626     77       4    A5 2002    ABBA  36 1.030 100.90370
627   1190      18    D4 2002    PIMA  44 0.455  64.09520
628   1204      19    D5 2002    PIMA  91 0.170  54.75780
629   2037      32    H3 2002    BEPA  71 1.425 100.36500
630   1556      24    F1 2002    ABBA  35 2.412  51.89675
631   1296      20    D6 2002    PIMA  58 0.335  57.92240
632    745      11    B6 2002    ABBA  25 0.830  55.66595
633    324       7    B2 2002    POTR  26 0.300  58.12000
634    848      12    C1 2002    ABBA  15 2.440  53.62525
635   1867      30    H1 2002    ACRU  65 0.784  58.06800
636    400       7    B2 2002    POTR  31 0.305  52.24000
637    854      12    C1 2002    ABBA  12 2.430  34.79205
638   2079      33    H4 2002    ABBA  37 0.516  60.55965
639    212       6    B1 2002    PIMA  54 1.050 100.78600
640   1873      30    H1 2002    ACSA  69 0.450  45.76500
641   1766      28    G2 2002    ACSA  81 0.145 130.14500
642   1458      22    E2 2002    QURU 106 0.620  96.02500
643   2074      33    H4 2002    BEPA  88 0.307  94.94300
644   1078      17    D3 2002    THOC 136 0.780 120.90000
645   1974      31    H2 2002    ACRU  42 1.169  68.75000
646    790      12    C1 2002    BEPA  63 1.415 107.90300
647   2190      34    H5 2002    PIMA  34 0.868  68.76740
648   1492      22    E2 2002    QURU 101 0.935 137.41000
649    637      10    B5 2002    PIBA  54 1.990 125.96200
650   1092      17    D3 2002    PIMA  63 1.200  51.10100
651   1605      25    F2 2002    ACSA  22 2.323  81.02600
652    627      10    B5 2002    PIBA  56 0.310  84.56300
653   2277      35    H6 2002    PIGL  27 1.350  59.71800
654    356       7    B2 2002    POTR  27 0.305  60.61500
655    445       8    B3 2002    PIMA  23 0.570  48.14460
656   1774      28    G2 2002    ACSA  56 0.335  78.10000
657    471       8    B3 2002    PIBA  21 2.175  96.57700
658    532       9    B4 2002    BEPA 102 0.795  84.19000
659    463       8    B3 2002    PIBA  22 1.360  79.83300
660   1251      20    D6 2002    PIMA  62 0.470  77.08500
661    452       8    B3 2002    PIBA  22 1.165  61.23600
662   1957      31    H2 2002    POTR  62 1.050 125.40000
663   1314      20    D6 2002    PIMA  63 0.420  55.45620
664    662      10    B5 2002    PIGL  54 0.480  61.23200
665    948      13    C2 2002    BEPA  57 0.410  43.99800
666    889      12    C1 2002    BEPA  71 0.780 112.06000
667   1306      20    D6 2002    PIMA  71 0.000  57.54880
668     34       3    A4 2002    PIST  62 1.205 124.98500
669   1192      18    D4 2002    PIMA  34 0.540  44.31720
670    866      12    C1 2002    ABBA  15 2.055  41.38420
671   1243      20    D6 2002    PIMA  69 0.405  48.75060
672    903      12    C1 2002    POTR  14 0.670  38.41500
673    364       7    B2 2002    PIBA  27 1.345  63.26500
674    131       5    A6 2002    BEPA  79 0.035  73.55800
675    253       6    B1 2002    PIBA  33 0.585  88.68600
676    335       7    B2 2002    PIBA  26 0.990  52.21100
677    280       7    B2 2002    ACRU  32 1.155  64.20000
678   1283      20    D6 2002    PIMA  67 0.255  72.74200
679    653      10    B5 2002    PIBA  51 1.360  86.97800
680    196       6    B1 2002    BEPA  44 0.080  61.93300
681    975      13    C2 2002    PIGL  54 0.525 102.61600
682   1044      15    D1 2002    THOC 164 0.630 125.35000
683    148       5    A6 2002    PIMA  78 0.125  84.45960
684    586      10    B5 2002    BEPA  60 0.840  41.82900
685    287       7    B2 2002    PIBA  28 0.460  94.76600
686   1499      23    E3 2002    QURU  58 1.345  84.39500
687    281       7    B2 2002    BEPA  22 0.185  54.96900</code></pre>
</div>
</div>
</section>
<section id="there-are-687-trees-in-a-30-sample-of-2002." class="level2">
<h2 class="anchored" data-anchor-id="there-are-687-trees-in-a-30-sample-of-2002.">There are 687 trees in a 30% sample of 2002.</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="co">#8</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>tree_dat <span class="sc">%&gt;%</span></span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(standID <span class="sc">==</span> <span class="dv">5</span>, year <span class="sc">==</span> <span class="dv">2007</span>) <span class="sc">%&gt;%</span></span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(rad_ib)) <span class="sc">%&gt;%</span></span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">slice_head</span>(<span class="at">n =</span> <span class="dv">3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  treeID standID stand year species age   inc   rad_ib
1    128       5    A6 2007    PIST  82 0.885 238.8850
2    157       5    A6 2007    PIRE  85 0.900 217.8700
3    135       5    A6 2007    PIMA  84 0.110 210.1874</code></pre>
</div>
</div>
</section>
<section id="the-treeids-are-128-157-and-135." class="level2">
<h2 class="anchored" data-anchor-id="the-treeids-are-128-157-and-135.">The treeIDs are 128, 157, and 135.</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="co">#9</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>tree_dat <span class="sc">%&gt;%</span></span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(treeID, standID, year, rad_ib) <span class="sc">%&gt;%</span></span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(standID <span class="sc">==</span> <span class="dv">3</span>, year <span class="sc">==</span> <span class="dv">2007</span>) <span class="sc">%&gt;%</span></span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">slice_min</span>(<span class="at">order_by =</span> rad_ib, <span class="at">n =</span> <span class="dv">3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  treeID standID year rad_ib
1     50       3 2007 47.396
2     56       3 2007 48.440
3     36       3 2007 54.925</code></pre>
</div>
</div>
</section>
<section id="the-three-trees-with-the-smallest-radius-at-breast-height-in-2007-are-shown-above-in-the-table-treeid-50-56-and-36." class="level2">
<h2 class="anchored" data-anchor-id="the-three-trees-with-the-smallest-radius-at-breast-height-in-2007-are-shown-above-in-the-table-treeid-50-56-and-36.">The three trees with the smallest radius at breast height in 2007 are shown above in the table, treeID 50, 56, and 36.</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="co">#10</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>tree_dat <span class="sc">%&gt;%</span></span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(treeID, year, rad_ib) <span class="sc">%&gt;%</span></span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">glimpse</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 131,386
Columns: 3
$ treeID &lt;int&gt; 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, …
$ year   &lt;int&gt; 1960, 1961, 1962, 1963, 1964, 1965, 1966, 1967, 1968, 1969, 197…
$ rad_ib &lt;dbl&gt; 10.78145, 11.73145, 12.71645, 13.70145, 14.41645, 15.25645, 15.…</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="co">#11</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>tree_dat <span class="sc">%&gt;%</span></span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">select</span>(<span class="fu">contains</span>(<span class="st">"ID"</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">glimpse</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 131,386
Columns: 2
$ treeID  &lt;int&gt; 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,…
$ standID &lt;int&gt; 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,…</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="co">#12</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>tree_dat <span class="sc">%&gt;%</span></span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">select</span>(<span class="fu">contains</span>(<span class="st">"ID"</span>) <span class="sc">|</span> <span class="fu">contains</span>(<span class="st">"stand"</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">glimpse</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 131,386
Columns: 3
$ treeID  &lt;int&gt; 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,…
$ standID &lt;int&gt; 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,…
$ stand   &lt;chr&gt; "A1", "A1", "A1", "A1", "A1", "A1", "A1", "A1", "A1", "A1", "A…</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="co">#13</span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>tree_dat <span class="ot">&lt;-</span> tree_dat <span class="sc">%&gt;%</span></span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(<span class="at">rad_ib_mm =</span> rad_ib, <span class="at">inc_mm =</span> inc) <span class="sc">%&gt;%</span></span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">glimpse</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 131,386
Columns: 8
$ treeID    &lt;int&gt; 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, …
$ standID   &lt;int&gt; 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, …
$ stand     &lt;chr&gt; "A1", "A1", "A1", "A1", "A1", "A1", "A1", "A1", "A1", "A1", …
$ year      &lt;int&gt; 1960, 1961, 1962, 1963, 1964, 1965, 1966, 1967, 1968, 1969, …
$ species   &lt;chr&gt; "ABBA", "ABBA", "ABBA", "ABBA", "ABBA", "ABBA", "ABBA", "ABB…
$ age       &lt;int&gt; 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 1…
$ inc_mm    &lt;dbl&gt; 0.930, 0.950, 0.985, 0.985, 0.715, 0.840, 0.685, 0.940, 1.16…
$ rad_ib_mm &lt;dbl&gt; 10.78145, 11.73145, 12.71645, 13.70145, 14.41645, 15.25645, …</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="co">#14</span></span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>tree_dat <span class="ot">&lt;-</span> tree_dat <span class="sc">%&gt;%</span></span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">rad_ib_cm =</span> rad_ib_mm <span class="sc">/</span> <span class="dv">10</span>)</span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb34-5"><a href="#cb34-5" aria-hidden="true" tabindex="-1"></a>tree_dat <span class="ot">&lt;-</span> tree_dat <span class="sc">%&gt;%</span></span>
<span id="cb34-6"><a href="#cb34-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">ba_m2 =</span> <span class="fl">0.00007854</span> <span class="sc">*</span> rad_ib_cm)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>tree_dat <span class="sc">%&gt;%</span></span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(species <span class="sc">==</span> <span class="st">"POTR"</span>, year <span class="sc">==</span> <span class="dv">2007</span>) <span class="sc">%&gt;%</span></span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">mean_ba =</span> <span class="fu">mean</span>(ba_m2, <span class="at">na.rm =</span> <span class="cn">TRUE</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       mean_ba
1 0.0007883588</code></pre>
</div>
</div>
</section>
<section id="the-mean-ba_m2-of-the-populus-tremuloides-species-is-0.0007883588-in-2007" class="level2">
<h2 class="anchored" data-anchor-id="the-mean-ba_m2-of-the-populus-tremuloides-species-is-0.0007883588-in-2007">The mean BA_m2 of the Populus tremuloides species is 0.0007883588 in 2007</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="co">#15</span></span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>tree_dat <span class="sc">%&gt;%</span></span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">established =</span> <span class="fu">if_else</span>(age <span class="sc">&gt;</span> <span class="dv">5</span>, <span class="cn">TRUE</span>, <span class="cn">FALSE</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(established)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  established      n
1       FALSE   8883
2        TRUE 122503</code></pre>
</div>
</div>
</section>
<section id="there-are-122503-established-trees-and-8883-unestablished-trees-less-than-5-years-old" class="level2">
<h2 class="anchored" data-anchor-id="there-are-122503-established-trees-and-8883-unestablished-trees-less-than-5-years-old">There are 122503 established trees and 8883 unestablished trees (less than 5 years old)</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="co">#16</span></span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a>tree_dat <span class="sc">%&gt;%</span></span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">DBH_class =</span> <span class="fu">case_when</span>(</span>
<span id="cb39-4"><a href="#cb39-4" aria-hidden="true" tabindex="-1"></a>    rad_ib_cm <span class="sc">&lt;=</span> <span class="fl">2.5</span> <span class="sc">~</span> <span class="st">"seedling"</span>,</span>
<span id="cb39-5"><a href="#cb39-5" aria-hidden="true" tabindex="-1"></a>    rad_ib_cm <span class="sc">&gt;</span> <span class="fl">2.5</span> <span class="sc">&amp;</span> rad_ib_cm <span class="sc">&lt;=</span> <span class="dv">10</span> <span class="sc">~</span> <span class="st">"sapling"</span>,</span>
<span id="cb39-6"><a href="#cb39-6" aria-hidden="true" tabindex="-1"></a>    rad_ib_cm <span class="sc">&gt;</span> <span class="dv">10</span> <span class="sc">&amp;</span> rad_ib_cm <span class="sc">&lt;=</span> <span class="dv">30</span> <span class="sc">~</span> <span class="st">"pole"</span>,</span>
<span id="cb39-7"><a href="#cb39-7" aria-hidden="true" tabindex="-1"></a>    rad_ib_cm <span class="sc">&gt;</span> <span class="dv">30</span> <span class="sc">~</span> <span class="st">"sawlog"</span></span>
<span id="cb39-8"><a href="#cb39-8" aria-hidden="true" tabindex="-1"></a>    )) <span class="sc">%&gt;%</span></span>
<span id="cb39-9"><a href="#cb39-9" aria-hidden="true" tabindex="-1"></a>      <span class="fu">filter</span>(year <span class="sc">==</span> <span class="dv">2007</span>) <span class="sc">%&gt;%</span></span>
<span id="cb39-10"><a href="#cb39-10" aria-hidden="true" tabindex="-1"></a>      <span class="fu">count</span>(DBH_class)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  DBH_class    n
1      pole  473
2   sapling 1817
3    sawlog    1</code></pre>
</div>
</div>
</section>
<section id="there-are-473-poles-1817-saplings-and-1-sawlog-in-2007." class="level2">
<h2 class="anchored" data-anchor-id="there-are-473-poles-1817-saplings-and-1-sawlog-in-2007.">There are 473 poles, 1817 saplings, and 1 sawlog in 2007.</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="co">#17</span></span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a>tree_dat <span class="sc">%&gt;%</span></span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(year <span class="sc">==</span> <span class="dv">2007</span>) <span class="sc">%&gt;%</span></span>
<span id="cb41-4"><a href="#cb41-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">mean_rad_ib =</span> <span class="fu">mean</span>(rad_ib_cm), <span class="at">sd_rad_ib =</span> <span class="fu">sd</span>(rad_ib_cm))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  mean_rad_ib sd_rad_ib
1    8.046755  3.069321</code></pre>
</div>
</div>
</section>
<section id="the-mean-breast-radius-was-8.046755cm-in-2007.-this-suggests-that-the-average-tree-in-2007-would-be-considered-a-sapling-which-is-consistent-with-the-results-from-question-16.-the-standard-deviation-was-3.069321cm-indicating-that-68-of-the-trees-will-have-a-dbh-between-4.98-cm-and-11.12-cm.-this-is-again-consistent-with-question-16-as-the-second-largest-dbh-class-was-pole-the-next-grouping-larger-than-sapling.-since-no-trees-measured-were-seedlings-this-suggests-a-somewhat-normal-distribution-but-with-a-right-skew." class="level2">
<h2 class="anchored" data-anchor-id="the-mean-breast-radius-was-8.046755cm-in-2007.-this-suggests-that-the-average-tree-in-2007-would-be-considered-a-sapling-which-is-consistent-with-the-results-from-question-16.-the-standard-deviation-was-3.069321cm-indicating-that-68-of-the-trees-will-have-a-dbh-between-4.98-cm-and-11.12-cm.-this-is-again-consistent-with-question-16-as-the-second-largest-dbh-class-was-pole-the-next-grouping-larger-than-sapling.-since-no-trees-measured-were-seedlings-this-suggests-a-somewhat-normal-distribution-but-with-a-right-skew.">The mean breast radius was 8.046755cm in 2007. This suggests that the average tree in 2007 would be considered a sapling, which is consistent with the results from question 16. The standard deviation was 3.069321cm, indicating that 68% of the trees will have a DBH between ~4.98 cm and 11.12 cm. This is again consistent with question 16, as the second largest DBH class was pole, the next grouping larger than sapling. Since no trees measured were seedlings, this suggests a somewhat normal distribution but with a right skew.</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="co">#18</span></span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a>tree_dat <span class="sc">%&gt;%</span></span>
<span id="cb43-3"><a href="#cb43-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(year <span class="sc">==</span> <span class="dv">2003</span>) <span class="sc">%&gt;%</span></span>
<span id="cb43-4"><a href="#cb43-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(species) <span class="sc">%&gt;%</span></span>
<span id="cb43-5"><a href="#cb43-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">species_mean_age =</span> <span class="fu">mean</span>(age, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb43-6"><a href="#cb43-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(species_mean_age)) <span class="sc">%&gt;%</span></span>
<span id="cb43-7"><a href="#cb43-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">slice_head</span>(<span class="at">n =</span> <span class="dv">3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 2
  species species_mean_age
  &lt;chr&gt;              &lt;dbl&gt;
1 THOC               127. 
2 FRNI                83.1
3 PIST                73.3</code></pre>
</div>
</div>
</section>
<section id="the-species-with-the-highest-mean-ages-in-2003-are-thuja-occidentalis-fraxinus-nigra-and-pinus-strobus" class="level2">
<h2 class="anchored" data-anchor-id="the-species-with-the-highest-mean-ages-in-2003-are-thuja-occidentalis-fraxinus-nigra-and-pinus-strobus">The species with the highest mean ages in 2003 are Thuja occidentalis, Fraxinus nigra, and Pinus strobus</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="co">#19</span></span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a>tree_dat <span class="sc">%&gt;%</span></span>
<span id="cb45-3"><a href="#cb45-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(</span>
<span id="cb45-4"><a href="#cb45-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">unique_years =</span> <span class="fu">n_distinct</span>(year),</span>
<span id="cb45-5"><a href="#cb45-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">first_year =</span> <span class="fu">min</span>(year),</span>
<span id="cb45-6"><a href="#cb45-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">last_year =</span> <span class="fu">max</span>(year)</span>
<span id="cb45-7"><a href="#cb45-7" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  unique_years first_year last_year
1          111       1897      2007</code></pre>
</div>
</div>
</section>
<section id="the-data-collected-covers-111-unique-years-with-the-first-year-being-in-1897-and-the-last-year-in-2007." class="level2">
<h2 class="anchored" data-anchor-id="the-data-collected-covers-111-unique-years-with-the-first-year-being-in-1897-and-the-last-year-in-2007.">The data collected covers 111 unique years, with the first year being in 1897 and the last year in 2007.</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="co">#20</span></span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a>tree_dat <span class="sc">%&gt;%</span></span>
<span id="cb47-3"><a href="#cb47-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(standID) <span class="sc">%&gt;%</span></span>
<span id="cb47-4"><a href="#cb47-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">unique_years =</span> <span class="fu">n_distinct</span>(year)) <span class="sc">%&gt;%</span></span>
<span id="cb47-5"><a href="#cb47-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(unique_years <span class="sc">==</span> <span class="fu">max</span>(unique_years))<span class="sc">%&gt;%</span></span>
<span id="cb47-6"><a href="#cb47-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">print</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 5 × 2
  standID unique_years
    &lt;int&gt;        &lt;int&gt;
1       1          111
2      15          111
3      16          111
4      17          111
5      24          111</code></pre>
</div>
</div>
</section>
<section id="stands-1-15-16-17-and-24-are-tied-for-the-maximum-number-of-unique-years-recorded-at-111-the-total-span-of-the-data-collection-period." class="level2">
<h2 class="anchored" data-anchor-id="stands-1-15-16-17-and-24-are-tied-for-the-maximum-number-of-unique-years-recorded-at-111-the-total-span-of-the-data-collection-period.">Stands 1, 15, 16, 17, and 24 are tied for the maximum number of unique years recorded at 111, the total span of the data collection period.</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="co">#21</span></span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a>tree_dat <span class="sc">%&gt;%</span></span>
<span id="cb49-3"><a href="#cb49-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(species, treeID) <span class="sc">%&gt;%</span></span>
<span id="cb49-4"><a href="#cb49-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(treeID, year) <span class="sc">%&gt;%</span></span>
<span id="cb49-5"><a href="#cb49-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">annual_growth =</span> rad_ib_cm <span class="sc">-</span> <span class="fu">lag</span>(rad_ib_cm),</span>
<span id="cb49-6"><a href="#cb49-6" aria-hidden="true" tabindex="-1"></a>        <span class="at">total_growth_record =</span> <span class="fu">n_distinct</span>(year)) <span class="sc">%&gt;%</span></span>
<span id="cb49-7"><a href="#cb49-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(total_growth_record <span class="sc">&gt;=</span> <span class="dv">10</span>) <span class="sc">%&gt;%</span></span>
<span id="cb49-8"><a href="#cb49-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(species) <span class="sc">%&gt;%</span></span>
<span id="cb49-9"><a href="#cb49-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(</span>
<span id="cb49-10"><a href="#cb49-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">avg_growth =</span> <span class="fu">mean</span>(annual_growth, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb49-11"><a href="#cb49-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">sd_growth =</span> <span class="fu">sd</span>(annual_growth, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb49-12"><a href="#cb49-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(avg_growth)) <span class="sc">%&gt;%</span></span>
<span id="cb49-13"><a href="#cb49-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">slice_head</span>(<span class="at">n =</span> <span class="dv">3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 3
  species avg_growth sd_growth
  &lt;chr&gt;        &lt;dbl&gt;     &lt;dbl&gt;
1 PIRE         0.179     0.129
2 POTR         0.165     0.109
3 PIBA         0.163     0.123</code></pre>
</div>
</div>
</section>
<section id="the-three-species-with-the-fastest-average-growth-rate-are-pinus-resinosa-populus-tremuloides-and-pinus-banksiana" class="level2">
<h2 class="anchored" data-anchor-id="the-three-species-with-the-fastest-average-growth-rate-are-pinus-resinosa-populus-tremuloides-and-pinus-banksiana">The three species with the fastest average growth rate are Pinus resinosa, Populus tremuloides, and Pinus banksiana</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a>tree_dat <span class="sc">%&gt;%</span></span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(species, treeID) <span class="sc">%&gt;%</span></span>
<span id="cb51-3"><a href="#cb51-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(treeID, year) <span class="sc">%&gt;%</span></span>
<span id="cb51-4"><a href="#cb51-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">annual_growth =</span> rad_ib_cm <span class="sc">-</span> <span class="fu">lag</span>(rad_ib_cm),</span>
<span id="cb51-5"><a href="#cb51-5" aria-hidden="true" tabindex="-1"></a>        <span class="at">total_growth_record =</span> <span class="fu">n_distinct</span>(year)) <span class="sc">%&gt;%</span></span>
<span id="cb51-6"><a href="#cb51-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(total_growth_record <span class="sc">&gt;=</span> <span class="dv">10</span>) <span class="sc">%&gt;%</span></span>
<span id="cb51-7"><a href="#cb51-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(species) <span class="sc">%&gt;%</span></span>
<span id="cb51-8"><a href="#cb51-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(</span>
<span id="cb51-9"><a href="#cb51-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">avg_growth =</span> <span class="fu">mean</span>(annual_growth, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb51-10"><a href="#cb51-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">sd_growth =</span> <span class="fu">sd</span>(annual_growth, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb51-11"><a href="#cb51-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(avg_growth) <span class="sc">%&gt;%</span></span>
<span id="cb51-12"><a href="#cb51-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">slice_head</span>(<span class="at">n =</span> <span class="dv">3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 3
  species avg_growth sd_growth
  &lt;chr&gt;        &lt;dbl&gt;     &lt;dbl&gt;
1 LALA        0.0749    0.0564
2 THOC        0.0765    0.0455
3 QURU        0.0838    0.0434</code></pre>
</div>
</div>
</section>
<section id="the-three-species-with-the-slowest-average-growth-rate-are-larix-laricina-thuja-occidentalis-and-quercus-rubra." class="level2">
<h2 class="anchored" data-anchor-id="the-three-species-with-the-slowest-average-growth-rate-are-larix-laricina-thuja-occidentalis-and-quercus-rubra.">The three species with the slowest average growth rate are Larix laricina, Thuja occidentalis, and Quercus rubra.</h2>
</section>
<section id="a-picture-of-pinus-resinosa-the-fastest-growing-species-is-located-in-the-img-folder-as-well-as-below." class="level2">
<h2 class="anchored" data-anchor-id="a-picture-of-pinus-resinosa-the-fastest-growing-species-is-located-in-the-img-folder-as-well-as-below.">A picture of Pinus resinosa, the fastest growing species, is located in the img folder as well as below.</h2>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="img/pinus_resinosa.jpg" class="img-fluid figure-img"></p>
<figcaption>Pinus resinosa</figcaption>
</figure>
</div>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>